### ISSUE TITLE
Please write block api wiki 

### ISSUE THREAD

**Issue by intbyte-100** [KirboGames/S.A.U.W.-#1]
I’m interesting in creating of block, but I don’t know how to do it, so please write block api documentation

**Comment by KirboGames** [comment]
I already wrote a blocks wiki, but i forgot to add the correct link ~~oops~~. You can look at "pages"

**Comment by KirboGames** [comment]
Done, I added links to the blocks wiki

**Comment by KirboGames** [comment]
Oops, I forgot to write blocks wiki, but file is created.
