### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by IbremMiner837** [KirboGames/S.A.U.W.-#2]
**Describe the bug**
When you click on the top right green button or when you click anywhere on the screen, the game crashes 

**To Reproduce**
1. Click on the green button that I pressed (on the screen), or click anywhere on the screen 

**Expected behavior**
Any action other than crashing the game  :) 

**Screenshots**
![Screenshot_20220129-232019_SAUW](https://user-images.githubusercontent.com/47252083/151679416-46a78491-e432-4918-a80e-6f1711851a07.jpg)

**Platform**
- [x] Android
- [ ] Desktop

**Additional context**

**Comment by KirboGames** [comment]
Oh, I know about this problem, it happens because game is trying to get a block that does not exist. i will try to fix it tomorrow.
