### ISSUE TITLE
Peanut

### ISSUE THREAD

**Issue by KirboGames** [KirboGames/S.A.U.W.-#47]
**Is your feature request related to a problem? Please describe.**
Peanuts or chips? Chips are unhealthy and peanuts are not, but peanuts can be a problem for people with increased blood clotting. But this is not problem because Boris has the perfect health

**Describe the solution you'd like**
Please add ~~АРАХИС~~ Peanuts

**Additional context**
@IbremMiner837 we need your help :D

**Comment by IbremMiner837** [comment]
Окей :)
https://www.youtube.com/watch?v=I-imNyWc0s8

**Comment by IbremMiner837** [comment]
@IbremMiner837 Ай ай ай

**Comment by IbremMiner837** [comment]
@IbremMiner837 Ты че дурак

**Comment by IbremMiner837** [comment]
@IbremMiner837 Эээ, сам такой

**Comment by IbremMiner837** [comment]
@all, СПАМ АТАКА!!!!
