### ISSUE TITLE
Background for player state indicator 

### ISSUE THREAD

**Issue by IbremMiner837** [KirboGames/S.A.U.W.-#5]
**Is your feature request related to a problem? Please describe.**
The player status indicator, or rather the text, merges with yellow sand and the text is not visible 

**Describe the solution you'd like**
Make background for player status indicators 

**Describe alternatives you've considered**
Or change the color of the text of the player's status indicators depending on the background color of the game, in understandable words, make Dynamic color change 

**Additional context**
![Screenshot_20220130-122051_SAUW](https://user-images.githubusercontent.com/47252083/151697609-ff23c9d4-32ee-46b0-8b8e-1193fa85c13e.jpg)

**Comment by KirboGames** [comment]
![image](https://user-images.githubusercontent.com/62571450/151706725-6081f64a-5fcf-4cac-8fd6-db7084dcd9c8.png)

like that?

**Comment by IbremMiner837** [comment]
Wow, very good 👌

**Comment by KirboGames** [comment]
I want to try to make it a bit transparent :D

**Comment by IbremMiner837** [comment]
Okay, 50-80% it will be chic :)

**Comment by KirboGames** [comment]
:moyai: 
![image](https://user-images.githubusercontent.com/62571450/151707945-b9377b2c-0455-406b-b966-9b0faf4f7d19.png)

**Comment by IbremMiner837** [comment]
🗿🗿

**Comment by KirboGames** [comment]
I think it's done
![image](https://user-images.githubusercontent.com/62571450/151712465-036d0515-490d-43ca-824a-a94c335bbb7d.png)

**Comment by KirboGames** [comment]
I tried to make the HUD a bit transparent :moyai:

![image](https://user-images.githubusercontent.com/62571450/151836832-ad93a7b5-0891-4d7d-98ae-0191232a3e75.png)
