### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by IbremMiner837** [KirboGames/S.A.U.W.-#6]
**Describe the bug**
The text from the console goes beyond the console and the screen 

**To Reproduce**
1. Open console 
2. Enter the command, example: give("com.infinitybyte.super_stick", "item:super_stick", 1)

**Expected behavior**
Text does not go beyond the console and screen 

**Screenshots**
![Screenshot_20220130-123502_SAUW](https://user-images.githubusercontent.com/47252083/151698222-dea77efa-202e-46f1-a654-6917a8ec8df8.jpg)

**Platform**
- [x] Android
- [x] Desktop

**Additional context**

**Comment by KirboGames** [comment]
That is, buttons showing in the wrong direction is this normal? :D @JVMFrog/lazy-team
