### ISSUE TITLE
Creative Mode

### ISSUE THREAD

**Issue by IbremMiner837** [KirboGames/S.A.U.W.-#7]
**Is your feature request related to a problem? Please describe.**
Incorrect work of the console (issuance of items) 

**Describe the solution you'd like**
Add a creative mode, where all things will be available, including things from mods 

**Describe alternatives you've considered**

**Additional context**

**Comment by intbyte-100** [comment]
I support you in this initiative, add a creative mode

**Comment by KirboGames** [comment]
Ok, I will add creative mode in the next update :D
